# Generated by Django 5.1 on 2024-11-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banda', models.CharField(max_length=100)),
                ('musica', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='musica/fotos')),
                ('estilo', models.SmallIntegerField(choices=[(8, 'FUNK'), (7, 'REGGAE'), (9, 'COUNTRY'), (10, 'BLUES'), (4, 'JAZZ'), (5, 'SERTANEJO'), (6, 'MPB'), (3, 'HIP HOP/RAP'), (2, 'ROCK'), (1, 'POP')])),
            ],
        ),
    ]
