# Generated by Django 5.1 on 2024-11-30 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='estilo',
            field=models.SmallIntegerField(choices=[(2, 'ROCK'), (9, 'COUNTRY'), (6, 'MPB'), (4, 'JAZZ'), (1, 'POP'), (3, 'HIP HOP/RAP'), (8, 'FUNK'), (5, 'SERTANEJO'), (10, 'BLUES'), (7, 'REGGAE')]),
        ),
    ]
