# Generated by Django 5.1 on 2024-11-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0002_alter_musica_estilo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='estilo',
            field=models.SmallIntegerField(choices=[(5, 'SERTANEJO'), (9, 'COUNTRY'), (10, 'BLUES'), (8, 'FUNK'), (6, 'MPB'), (7, 'REGGAE'), (2, 'ROCK'), (4, 'JAZZ'), (1, 'POP'), (3, 'HIP HOP/RAP')]),
        ),
    ]
