# Generated by Django 5.1 on 2024-11-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0003_alter_musica_estilo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='estilo',
            field=models.SmallIntegerField(choices=[(1, 'POP'), (3, 'HIP HOP/RAP'), (6, 'MPB'), (5, 'SERTANEJO'), (10, 'BLUES'), (8, 'FUNK'), (7, 'REGGAE'), (2, 'ROCK'), (4, 'JAZZ'), (9, 'COUNTRY')]),
        ),
    ]
