# Generated by Django 5.1 on 2024-12-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0004_alter_musica_estilo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='estilo',
            field=models.SmallIntegerField(choices=[(9, 'COUNTRY'), (4, 'JAZZ'), (8, 'FUNK'), (10, 'BLUES'), (3, 'HIP HOP/RAP'), (1, 'POP'), (5, 'SERTANEJO'), (7, 'REGGAE'), (2, 'ROCK'), (6, 'MPB')]),
        ),
    ]
