# Generated by Django 5.1 on 2024-11-30 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musica', '0003_alter_musica_estilo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=200)),
                ('musicas', models.ManyToManyField(related_name='colecoes', to='musica.musica')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colecoes_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
