# Generated by Django 5.1 on 2024-11-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colecao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colecao',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='colecao/fotos'),
        ),
    ]
